[service]
name = "frontend"
start = "npm run start"
build = "npm ci && npm run build"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
