[service]
name = "frontend"
start = "node .next/standalone/server.js"
build = "npm ci && npm run build"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
