[service]
name = "backend"
start = "sh start.sh"
build = "npm ci && npx prisma generate && npm run build"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
