[service]
name = "backend"
start = "npx prisma migrate deploy && node dist/main.js"
build = "npm ci && npx prisma generate && npm run build"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
